export interface VietnamCity {
	name: string;
	code: string;
}

export const VIETNAM_CITIES: VietnamCity[] = [
	{ name: "An Giang", code: "AG" },
	{ name: "Bà Rịa - Vũng Tàu", code: "BR-VT" },
	{ name: "Bạc Liêu", code: "BL" },
	{ name: "Bắc Giang", code: "BG" },
	{ name: "Bắc Kạn", code: "BK" },
	{ name: "Bắc Ninh", code: "BN" },
	{ name: "Bến Tre", code: "BT" },
	{ name: "Bình Dương", code: "BD" },
	{ name: "Bình Định", code: "BDi" },
	{ name: "Bình Phước", code: "BP" },
	{ name: "Bình Thuận", code: "BTh" },
	{ name: "Cà Mau", code: "CM" },
	{ name: "Cao Bằng", code: "CB" },
	{ name: "Cần Thơ", code: "CT" },
	{ name: "Đà Nẵng", code: "DN" },
	{ name: "Đắk Lắk", code: "DL" },
	{ name: "Đắk Nông", code: "DNo" },
	{ name: "Điện Biên", code: "DB" },
	{ name: "Đồng Nai", code: "DonNai" },
	{ name: "Đồng Tháp", code: "DT" },
	{ name: "Gia Lai", code: "GL" },
	{ name: "Hà Giang", code: "HG" },
	{ name: "Hà Nam", code: "HNam" },
	{ name: "Hà Nội", code: "HN" },
	{ name: "Hà Tĩnh", code: "HT" },
	{ name: "Hải Dương", code: "HD" },
	{ name: "Hải Phòng", code: "HP" },
	{ name: "Hậu Giang", code: "HGi" },
	{ name: "Hòa Bình", code: "HB" },
	{ name: "Hưng Yên", code: "HY" },
	{ name: "Khánh Hòa", code: "KH" },
	{ name: "Kiên Giang", code: "KG" },
	{ name: "Kon Tum", code: "KT" },
	{ name: "Lai Châu", code: "LC" },
	{ name: "Lạng Sơn", code: "LS" },
	{ name: "Lào Cai", code: "LCa" },
	{ name: "Lâm Đồng", code: "LDo" },
	{ name: "Long An", code: "LA" },
	{ name: "Nam Định", code: "ND" },
	{ name: "Nghệ An", code: "NA" },
	{ name: "Ninh Bình", code: "NB" },
	{ name: "Ninh Thuận", code: "NT" },
	{ name: "Phú Thọ", code: "PT" },
	{ name: "Phú Yên", code: "PY" },
	{ name: "Quảng Bình", code: "QB" },
	{ name: "Quảng Nam", code: "QNam" },
	{ name: "Quảng Ngãi", code: "QNg" },
	{ name: "Quảng Ninh", code: "QNi" },
	{ name: "Quảng Trị", code: "QT" },
	{ name: "Sóc Trăng", code: "ST" },
	{ name: "Sơn La", code: "SL" },
	{ name: "Tây Ninh", code: "TN" },
	{ name: "Thái Bình", code: "TB" },
	{ name: "Thái Nguyên", code: "TNg" },
	{ name: "Thanh Hóa", code: "TH" },
	{ name: "Thừa Thiên Huế", code: "TTH" },
	{ name: "Tiền Giang", code: "TG" },
	{ name: "TP. Hồ Chí Minh", code: "HCM" },
	{ name: "Trà Vinh", code: "TV" },
	{ name: "Tuyên Quang", code: "TQ" },
	{ name: "Vĩnh Long", code: "VL" },
	{ name: "Vĩnh Phúc", code: "VP" },
	{ name: "Yên Bái", code: "YB" },
];
